wandb_version: 1

name:
  desc: null
  value: gcn-1047-egfxset
model_type:
  desc: null
  value: GCN
criterion1:
  desc: null
  value: stft
pre_emphasis:
  desc: null
  value: null
criterion2:
  desc: null
  value: smooth
dataset:
  desc: null
  value: egfxset
sample_rate:
  desc: null
  value: 48000
bit_rate:
  desc: null
  value: 24
optimizer:
  desc: null
  value: Adam
lr:
  desc: null
  value: 0.001
lr_scheduler:
  desc: null
  value: ReduceLROnPlateau
lr_patience:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 8
num_workers:
  desc: null
  value: 4
max_epochs:
  desc: null
  value: 1000
early_stop_patience:
  desc: null
  value: 100
current_epoch:
  desc: null
  value: 192
min_valid_loss:
  desc: null
  value: 0.9417729237500359
cond_dim:
  desc: null
  value: 3
c0:
  desc: null
  value: 0.0
c1:
  desc: null
  value: 0.0
c2:
  desc: null
  value: 0.0
in_ch:
  desc: null
  value: 1
out_ch:
  desc: null
  value: 1
n_blocks:
  desc: null
  value: 2
n_channels:
  desc: null
  value: 32
dilation_growth:
  desc: null
  value: 512
kernel_size:
  desc: null
  value: 99
timestamp:
  desc: null
  value: 20240226-231835
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709016978.63281
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
