name: LSTM-3
model_type: LSTM

criterion1: stft
pre_emphasis: null
criterion2: smooth

optimizer: Adam
lr: 0.01
lr_scheduler: ReduceLROnPlateau
lr_patience: 10

max_epochs: 500
early_stop_patience: 50
current_epoch: 0

min_valid_loss: null

cond_dim: 2
c0 : 0.0
c1 : 0.0

input_size: 1
hidden_size: 16
n_layers: 2
output_size: 1
dropout_prob: 0.5
use_skip: True
kernel_size: 3

