name: WaveNet-99
model_type: WaveNet

criterion1: stft
pre_emphasis: null
criterion2: smooth

optimizer: Adam
lr: 0.01
lr_scheduler: ReduceLROnPlateau
lr_patience: 10

max_epochs: 500
early_stop_patience: 50
current_epoch: 0

min_valid_loss: null

cond_dim: 2
c0: 0.0
c1: 0.0

# WaveNet
in_ch: 1
out_ch: 1
n_blocks: 2
n_stacks: 2
n_channels: 16
dilation_growth: 10
kernel_size: 3

