wandb_version: 1

name:
  desc: null
  value: TCN
model_type:
  desc: null
  value: TCN
criterion1:
  desc: null
  value: stft
pre_emphasis:
  desc: null
  value: null
criterion2:
  desc: null
  value: smooth
optimizer:
  desc: null
  value: Adam
lr:
  desc: null
  value: 0.01
lr_scheduler:
  desc: null
  value: ReduceLROnPlateau
lr_patience:
  desc: null
  value: 10
max_epochs:
  desc: null
  value: 500
early_stop_patience:
  desc: null
  value: 50
current_epoch:
  desc: null
  value: 127
min_valid_loss:
  desc: null
  value: 1.7596818378993444
cond_dim:
  desc: null
  value: 2
c0:
  desc: null
  value: 0.0
c1:
  desc: null
  value: 0.0
in_ch:
  desc: null
  value: 1
out_ch:
  desc: null
  value: 1
n_channels:
  desc: null
  value: 32
n_layers:
  desc: null
  value: 5
dilation_growth:
  desc: null
  value: 14
kernel_size:
  desc: null
  value: 3
dataset:
  desc: null
  value: springset
sample_rate:
  desc: null
  value: 16000
bit_depth:
  desc: null
  value: 16
batch_size:
  desc: null
  value: 64
num_workers:
  desc: null
  value: 8
timestamp:
  desc: null
  value: 20240228-144622
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711303206.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
