name: gru-4-c2-eg-all
model_type: GRU

criterion1: mrstft
pre_emphasis: null
criterion2: smooth

dataset: egfxset
sample_rate: 48000
bit_rate: 24

optimizer: Adam
lr: 0.005
lr_scheduler: ReduceLROnPlateau
lr_patience: 20

batch_size: 4
num_workers: 4

max_epochs: 1000
early_stop_patience: 100
current_epoch: 0

min_valid_loss: null

cond_dim: 2
c0 : 1.0
c1 : 1.0

kernel_size: 3

num_layers: 4
input_size: 1
output_size: 1
hidden_size: 32
dropout_prob: 0.5
use_skip: True


