name: wavenet-1k5
model_type: WaveNet

criterion1: mrstft
pre_emphasis: null
criterion2: mae

dataset: egfxset
sample_rate: 48000
bit_rate: 24

optimizer: Adam
lr: 0.005
lr_scheduler: ReduceLROnPlateau
lr_patience: 10

batch_size: 4
num_workers: 4

max_epochs: 1000
early_stop_patience: 55
current_epoch: 0

min_valid_loss: null

cond_dim: 2

# WaveNet
num_channels: 16
dilation_depth: 10
num_repeat: 5
kernel_size: 5
