wandb_version: 1

name:
  desc: null
  value: gru-conv-4-springset
model_type:
  desc: null
  value: GRU
criterion1:
  desc: null
  value: stft
pre_emphasis:
  desc: null
  value: null
criterion2:
  desc: null
  value: smooth
dataset:
  desc: null
  value: springset
sample_rate:
  desc: null
  value: 16000
bit_rate:
  desc: null
  value: 16
optimizer:
  desc: null
  value: Adam
lr:
  desc: null
  value: 0.001
lr_scheduler:
  desc: null
  value: ReduceLROnPlateau
lr_patience:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 64
num_workers:
  desc: null
  value: 4
max_epochs:
  desc: null
  value: 1000
early_stop_patience:
  desc: null
  value: 100
current_epoch:
  desc: null
  value: 0
min_valid_loss:
  desc: null
  value: null
cond_dim:
  desc: null
  value: 3
c0:
  desc: null
  value: 0.0
c1:
  desc: null
  value: 0.0
c2:
  desc: null
  value: 0.0
input_size:
  desc: null
  value: 1
hidden_size:
  desc: null
  value: 64
n_layers:
  desc: null
  value: 4
output_size:
  desc: null
  value: 1
dropout_prob:
  desc: null
  value: 0.5
use_skip:
  desc: null
  value: true
kernel_size:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708977116.61314
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
