name: GRU
model_type: GRU

criterion1: stft
pre_emphasis: null
criterion2: smooth

optimizer: Adam
lr: 0.001
lr_scheduler: ReduceLROnPlateau
lr_patience: 20

batch_size: 8
num_workers: 4

max_epochs: 1000
early_stop_patience: 100
current_epoch: 0

min_valid_loss: null

cond_dim: 2
c0 : 0.0
c1 : 0.0

input_size: 1
hidden_size: 64
n_layers: 4
output_size: 1
dropout_prob: 0.5
use_skip: True
kernel_size: 3



