name: gcn-2500-bx-c2
model_type: GCN_FiLM

criterion1: mrstft
pre_emphasis: null
criterion2: smooth

dataset: customset
sample_rate: 48000
bit_rate: 24

optimizer: Adam
lr: 0.005
lr_scheduler: ReduceLROnPlateau
lr_patience: 10

batch_size: 8
num_workers: 4

max_epochs: 1000
early_stop_patience: 50
current_epoch: 0

min_valid_loss: null

cond_dim: 2
c0 : 0.5
c1 : 0.5

kernel_size: 5
num_blocks: 1
num_channels: 16
dilation_depth: 3
num_layers: 10
num_repeat: 0
input_size: 1
output_size: 1
hidden_size: 0

