name: wavenet-24-nocf
model_type: WaveNet

criterion1: stft
pre_emphasis: null
criterion2: smooth

dataset: egfxset
sample_rate: 48000
bit_rate: 24

optimizer: Adam
lr: 0.001
lr_scheduler: ReduceLROnPlateau
lr_patience: 10

batch_size: 4
num_workers: 4

max_epochs: 1000
early_stop_patience: 70
current_epoch: 0

min_valid_loss: null

cond_dim: 2
c0 : 0.0
c1 : 0.0

num_channels: 32
dilation_depth: 8
num_repeat: 3
kernel_size: 3
