# _config.yml

title: Neural Audio Effect Modelling Strategies for a Spring Reverb
author:
  name: Francesco Papaleo
  email: name.surname {at} gmail.com

description: >
  Repository for the MSc thesis in Sound and Music Computing at the Music Technology Group, Universitat Pompeu Fabra, Barcelona, Spain.

header_pages:
  - index.md
  - about.md
  - resources.md

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/francescopapaleo" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/francescopapaleo/" }